MODULE constants
    IMPLICIT NONE
    INTEGER, PARAMETER      :: RP = SELECTED_REAL_KIND(15)
    INTEGER, PARAMETER      :: NONE=-1
    REAL(KIND=RP),PARAMETER :: pi = 4.0_RP*ATAN(1.0_RP)
END MODULE constants
